name: Export Draw.io diagrams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Draw.io (diagrams.net) CLI
        run: |
          curl -L -o drawio.AppImage https://github.com/jgraph/drawio-desktop/releases/download/v21.7.2/drawio-x86_64-21.7.2.AppImage
          chmod +x drawio.AppImage

      - name: Export .drawio to PNG and SVG
        run: |
          for file in $(find . -name "*.drawio"); do
            base="${file%.drawio}"
            echo "Exporting $file..."
            ./drawio.AppImage --export "$file" --output "${base}.drawio.png" --format png
            ./drawio.AppImage --export "$file" --output "${base}.drawio.svg" --format svg
          done

      - name: Commit and push exported files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add *.drawio.png *.drawio.svg || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-export Draw.io diagrams"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
