name: Export Draw.io diagrams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t drawio-exporter .

      - name: Run drawio-export in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            drawio-exporter

      - name: Commit & push exported files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add *.drawio.png *.drawio.svg || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto-export Draw.io diagrams"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
